# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 10:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('show_name', models.CharField(max_length=200)),
                ('cell', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('comments', models.TextField()),
                ('firstname', models.CharField(default='', max_length=200)),
                ('surname', models.CharField(default='', max_length=200)),
                ('car_registration', models.CharField(default='', max_length=20)),
                ('flagstatus', models.BooleanField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ContractorFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', stdimage.models.StdImageField(blank=True, upload_to='documents/%Y/%m/%d')),
                ('title', models.CharField(default='', max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DocummentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('show_name', models.CharField(max_length=200)),
                ('cell', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('comments', models.TextField()),
                ('flagstatus', models.BooleanField(default=0)),
                ('firstname', models.CharField(default='', max_length=200)),
                ('surname', models.CharField(default='', max_length=200)),
                ('car_registration', models.CharField(default='', max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('street_address', models.CharField(default='', max_length=200)),
                ('suburb', models.CharField(default='', max_length=200)),
                ('province', models.CharField(default='', max_length=200)),
                ('show_name', models.CharField(default='', max_length=200)),
                ('postal_code', models.CharField(default='', max_length=200)),
                ('EntityRegistrationNumber', models.CharField(default='', max_length=200)),
                ('OfficePhone', models.CharField(default='', max_length=200)),
                ('office_cell', models.CharField(max_length=200)),
                ('office_email', models.CharField(max_length=200)),
                ('comments', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.EntityType')),
            ],
        ),
        migrations.CreateModel(
            name='inventoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSouthAfrican', models.BooleanField(default=0)),
                ('SAidentityNo', models.CharField(blank=True, max_length=13, null=True)),
                ('PassportNo', models.CharField(max_length=200)),
                ('show_name', models.CharField(default='', max_length=50)),
                ('firstname', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=200)),
                ('cellPhoneNumber', models.CharField(default='', max_length=20)),
                ('emailAddress', models.EmailField(default='', max_length=254, null=True)),
                ('car_registration', models.CharField(default='', max_length=20)),
                ('flagstatus', models.BooleanField(default=0)),
                ('comments', models.TextField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='GuestFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.inventory')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='GuestVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
                ('arrival_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.inventory')),
                ('guestname', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SAIDFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('said', models.CharField(blank=True, max_length=13, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='Salutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessinventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='notset', max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.inventory')),
                ('users_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('group',),
            },
        ),
        migrations.CreateModel(
            name='UserPerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_groups', models.ManyToManyField(default='', to='rentWareApp.UserGroup')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='guestflag',
            name='offense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Offense'),
        ),
        migrations.AddField(
            model_name='guest',
            name='nationality',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Nationality'),
        ),
        migrations.AddField(
            model_name='guest',
            name='salutation',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Salutation'),
        ),
        migrations.AddField(
            model_name='guest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guest',
            name='visatype',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.VisaType'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventorytype',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.inventoryType'),
        ),
        migrations.AddField(
            model_name='employeeflag',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.inventory'),
        ),
        migrations.AddField(
            model_name='employeeflag',
            name='offense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Offense'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeetype',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.EmployeeType'),
        ),
        migrations.AddField(
            model_name='employee',
            name='inventory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.inventory'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.DocummentType'),
        ),
        migrations.AddField(
            model_name='document',
            name='guest',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Guest'),
        ),
        migrations.AddField(
            model_name='contractorflag',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.inventory'),
        ),
        migrations.AddField(
            model_name='contractorflag',
            name='offense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Offense'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contractortype',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.ContractorType'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='inventory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.inventory'),
        ),
    ]
