# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-28 08:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentWareApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSouthAfrican', models.BooleanField(default=0)),
                ('SAidentityNo', models.CharField(blank=True, max_length=13, null=True)),
                ('PassportNo', models.CharField(max_length=200)),
                ('show_name', models.CharField(default='', max_length=50)),
                ('firstname', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=200)),
                ('cellPhoneNumber', models.CharField(default='', max_length=20)),
                ('emailAddress', models.EmailField(default='', max_length=254, null=True)),
                ('car_registration', models.CharField(default='', max_length=20)),
                ('flagstatus', models.BooleanField(default=0)),
                ('comments', models.TextField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('nationality', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Nationality')),
                ('salutation', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Salutation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='contractorflag',
            name='author',
        ),
        migrations.RemoveField(
            model_name='contractorflag',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='contractorflag',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='contractorflag',
            name='offense',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='salutation',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='visatype',
        ),
        migrations.RemoveField(
            model_name='guestflag',
            name='author',
        ),
        migrations.RemoveField(
            model_name='guestflag',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='guestflag',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='guestflag',
            name='offense',
        ),
        migrations.RemoveField(
            model_name='saidflags',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='document',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='employeeflag',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='guestvisit',
            name='guestname',
        ),
        migrations.RemoveField(
            model_name='guestvisit',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='EntityRegistrationNumber',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='OfficePhone',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='office_cell',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='office_email',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='province',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='show_name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='suburb',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='trading_name',
        ),
        migrations.RemoveField(
            model_name='useraccessinventory',
            name='inventory',
        ),
        migrations.DeleteModel(
            name='ContractorFlag',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='GuestFlag',
        ),
        migrations.DeleteModel(
            name='SAIDFlags',
        ),
    ]
