# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-28 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentWareApp', '0002_auto_20170328_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='contractortype',
        ),
        migrations.RemoveField(
            model_name='contractortype',
            name='author',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='docummenttype',
            name='author',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employeetype',
        ),
        migrations.RemoveField(
            model_name='employeeflag',
            name='author',
        ),
        migrations.RemoveField(
            model_name='employeeflag',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeflag',
            name='offense',
        ),
        migrations.RemoveField(
            model_name='employeetype',
            name='author',
        ),
        migrations.RemoveField(
            model_name='entitytype',
            name='author',
        ),
        migrations.RemoveField(
            model_name='guestvisit',
            name='author',
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='author',
        ),
        migrations.RemoveField(
            model_name='offense',
            name='author',
        ),
        migrations.RemoveField(
            model_name='useraccessinventory',
            name='users_inventory',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='author',
        ),
        migrations.RemoveField(
            model_name='userperm',
            name='author',
        ),
        migrations.RemoveField(
            model_name='userperm',
            name='user_groups',
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='author',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='surname',
            new_name='AccountCode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='PassportNo',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='SAidentityNo',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='car_registration',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cellPhoneNumber',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='emailAddress',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='flagstatus',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='isSouthAfrican',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='salutation',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='show_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='CompanyName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='VATNumber',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='inventory',
            name='partID',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='comments',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
        migrations.DeleteModel(
            name='ContractorType',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocummentType',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeFlag',
        ),
        migrations.DeleteModel(
            name='EmployeeType',
        ),
        migrations.DeleteModel(
            name='EntityType',
        ),
        migrations.DeleteModel(
            name='GuestVisit',
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
        migrations.DeleteModel(
            name='Offense',
        ),
        migrations.DeleteModel(
            name='Salutation',
        ),
        migrations.DeleteModel(
            name='UserAccessinventory',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
        migrations.DeleteModel(
            name='UserPerm',
        ),
        migrations.DeleteModel(
            name='VisaType',
        ),
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Contact'),
        ),
        migrations.AddField(
            model_name='customer',
            name='uploads',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Upload'),
        ),
    ]
