# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-22 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentWareApp', '0002_auto_20170522_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
