# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-17 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentWareApp', '0004_comment_image_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Customer'),
        ),
        migrations.AddField(
            model_name='image',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Customer'),
        ),
        migrations.AddField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Customer'),
        ),
        migrations.AddField(
            model_name='typecontact',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentWareApp.Customer'),
        ),
    ]
