# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-25 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentWareApp', '0009_rate_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='partID',
            field=models.CharField(default='', max_length=10),
        ),
    ]
