# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-24 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentWareApp', '0009_image_imagefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telephone',
            name='shirt_size',
        ),
        migrations.AddField(
            model_name='telephone',
            name='TypeofTelephone',
            field=models.CharField(choices=[('P', 'Personal Cellphone'), ('C', 'Private Cellphone'), ('S', 'Standby Cellphone'), ('O', 'Office Landline'), ('K', 'Inquiries Landline'), ('H', 'Home Landline'), ('Q', 'Direct Office Extension'), ('V', 'Virtual Phone')], default='O', max_length=1),
        ),
    ]
