# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-24 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentWareApp', '0010_auto_20170424_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='surnamename',
            new_name='surname',
        ),
    ]
