# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-24 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentWareApp', '0011_auto_20170424_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
