# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-02 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentWareApp', '0012_auto_20170424_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Telephone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
    ]
