# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-02 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentWareApp', '0014_auto_20170502_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='firstname',
            field=models.CharField(default='', max_length=200, verbose_name='Contacts first name'),
        ),
    ]
