# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-03 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentWareApp', '0015_auto_20170502_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
    ]
