# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-11 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentWareApp', '0016_auto_20170503_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='s',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='AccountCode',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
