# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-11 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentWareApp', '0017_auto_20170511_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='s',
            field=models.SlugField(unique=True),
        ),
    ]
