# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-11 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentWareApp', '0018_auto_20170511_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='s',
            new_name='slug',
        ),
    ]
