# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-12 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentWareApp', '0019_auto_20170511_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='partID',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
